base_url: https://prodmage.github.io/denverpsychologyandwellness.com
title: Denver Psychology and Wellness
email: drjohnbodycombe@gmail.com
phone_number: (303) 731-6149
address: "1805 South Bellaire Street, Suite 215-1, Denver, CO 80222"
description: > #
  JOOOOOHN

google_analytics_id: 
google_site_verification: 
google_maps_api_key: AIzaSyDGIu3uZ-LrrGOfaroZduUo_mnEtcGaB-Q

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - .gitignore
  - README.md