base_url: https://www.denverpsychologyandwellness.com
title: Denver Psychology and Wellness
email: drjohnbodycombe@gmail.com
phone_number: (303) 731-6149
address: "1805 South Bellaire Street, Suite 350, Denver, CO 80222"
description: > #
  Are you struggling with feeling overwhelmed, lost, or unsatisfied in your life?  Do these feelings impact your mood, your relationships, or your work?  I specialize in helping adults and emerging adults (18-50s) people work through these sorts of challenges that we all face at different times in our lives. Denver Psychology and Wellness provides quality individual, couples, and group therapy in Denver, CO.  Please contact us at 303-731-6149 or at info@denverpsychologyandwellness.com.

google_analytics_id: UA-107076154-1
google_site_verification: hqUSANTGJuX4noy_4uF6fzP1qoTdRXp9CRWkzkB3fkE
google_maps_api_key: AIzaSyDGIu3uZ-LrrGOfaroZduUo_mnEtcGaB-Q

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - .gitignore
  - README.md